### ISSUE TITLE
use api_handler post error

### ISSUE THREAD

**Issue by xhsiung** [fadushin/esp8266#12]
port data is
{
     "name":"alex",
     "test": "aaaa"
}

error: below
<html><body><header>uhttpd/master<hr></header>Bad Request Failed to load JSON: syntax error in JSON:<pre>Traceback (most recent call last):
  File "uhttpd.py", line 157, in handle_request
  File "http_api_handler.py", line 50, in handle_request
  File "http_api_handler.py", line 50, in handle_request
BadRequestException: Failed to load JSON: syntax error in JSON
</pre></body></html>

**Comment by fadushin** [comment]
The unit tests post data and currently pass.  Could you provide more information about how to reproduce this?
